### ISSUE TITLE
Consider splitting GHA workflows

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/enprot#51]
Each workflow represents a badge. Would we prefer having a separate badge per platform, instead of one badge encompassing all platforms?

**Comment by skalee** [comment]
IMHO splitting the workflows has several disadvantages:

1. It comes with a risk of badges proliferation. Right now there are three systems, but in future it may be more of them (e.g. via some kind of virtualization).
2. It is unnecessary. If given build fails for any system, the revision is considered broken, not partially good or something. If there are known bugs which are not expected to be fixed any soon, then we should mark failing tests as pending rather than ignore that test suite does not pass.
3. It requires copy-pasting most of the CI configuration. Not DRY at all, difficult to review, and error-prone.

**Comment by ronaldtse** [comment]
That's true, thanks for the comments. Closing.
